---
- name: Install Cognos Analytics
  hosts: all
  #become_method: dzdo
  #become_user: cgadm
  #become_flags: 'su - root -c'

  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: ../vars/main.yml
        
    - name: Copy Binary File
      copy:
        src: "{{ LOCAL_DIR }}ca_instl_lnxi38664_2.0.2003191.bin"
        dest: /apps/CognosAnalyticsPERF/ca_instl_lnxi38664_2.0.2003191.bin
        force: no
    
    - name: Copy Zip File
      copy:
        src: "{{ LOCAL_DIR }}ca.zip"
        dest: /apps/CognosAnalyticsPERF/ca.zip
        force: no

    - name: Copy over response file
      ansible.builtin.template:
        src: ../templates/responsefile.properties
        dest: /apps/CognosAnalyticsPERF

    - name: Run installer
      command: /apps/CognosAnalyticsPERF/ca_instl_lnxi38664_2.0.2003191.bin 
      args: ./setup -rsp responsefile.txt -verbose
        chdir: /opt/is-suite/
      